### ISSUE TITLE
Add TOML support

### ISSUE THREAD

**Issue by Defman21** [Defman21/prxpass-server#10]
TOML will replace most of the flags and leave `-tcp` and `-http` so an user would able to run different types of servers using the same config.

An example config file:

```toml
[http]
client = "0.0.0.0:8000"
server = "0.0.0.0:443"
host = "example.com"
custom_ids = false
[http.tls]
enabled = true
cert = "~/.acme.sh/example.com/example.com.cer"
key = "~/.acme.sh/example.com/example.com.key"

[tcp]
client = "0.0.0.0:9000"
server = "0.0.0.0:18000"
```
