### ISSUE TITLE
config.toml won't load values

### ISSUE THREAD

**Issue by bernhardberger** [Defman21/prxpass-server#12]
I just realized that your readme isn't up to date as you seem to have removed the flags feature (which is a shame as this would badly enhance docker usability).

However it won't load my toml values.

My build:
```dockerfile
FROM golang:latest

#RUN mkdir /app

RUN git clone https://github.com/Defman21/prxpass-server.git /go/src/app

#RUN go get github.com/Defman21/prxpass-server
WORKDIR /go/src/app

RUN go get -d -v
RUN go install -v

ADD config.toml .

CMD ["app", "-http"]

EXPOSE 8080
EXPOSE 80
```

My config.toml:
```toml
[http]
    client = "0.0.0.0:8000"
    server = "0.0.0.0:80"
    host = "tunnel.mydomain.tld"
    custom_ids = true
    password = "mysecret"
    [http.tls]
        enabled = false
        cert = ""
        key = ""
[tcp]
    client = "0.0.0.0:3000"
    server = "0.0.0.0:30"
    password = "mysecret"
```

Output after running `app -http`:
```bash
root@8b32137eca4e:/go/src/app# app -http
INFO[0000] Config                                        conf="{HTTP:{Client: Server: Host: CustomIDs:false TLS:{Enabled:false Cert: Key:} Password:} TCP:{Client: Server: Password:}}"
INFO[0000] Listening                                     host= https=false server=
```
